### ISSUE TITLE
Trying to add panel and update to grapesJS 0.16

### ISSUE THREAD

**Issue by j2l** [mavoweb/create#3]
Hello,
To be able to see generated Mavo code, I tried to adapt the GrapesJS `export` example from https://grapesjs.com/docs/getting-started.html#panels-buttons to the Create index.js syntax, I can display the export button using:
```
pnm.addButton('options', {
  id: 'export',
  className: 'btn-open-export',
  command: 'export-template',
      context: 'export-template',
  attributes: {
    'title': 'Show code to export',
    'data-tooltip-pos': 'bottom',
  }
});
```
But nothing happens when clicked, no error in browser or server, it seems that the internal function `export` was not implemented back then. The local GrapesJS of Create is 0.12 and nowadays GrapesJS is 0.16.

Replacing local  `/grapesjs` calls with:
```
<link rel="stylesheet" href="https://unpkg.com/grapesjs/dist/css/grapes.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.16.12/grapes.min.js"></script>
```
didn't do the trick :smirk: 
I'm not confident/good/reckless enough to adapt Create and/or grapesjs-mavo to GrapesJS 0.16 but it would be needed I guess.
@LeaVerou, what do you think?

**Comment by LeaVerou** [comment]
You can try to adapt it locally and see what happens. After all, this Create project is currently unmaintained after Francesca graduated, so the only way you can make it go is forwards!

**Comment by j2l** [comment]
I did and it failed.
With my limited coding skills, can't go forwards :(

**Comment by LeaVerou** [comment]
The best way to develop coding skills is to work on something you like. Don't give up!

**Comment by j2l** [comment]
You're right @LeaVerou, but I also need some help and drilling a 2 years old plugin and 2 projects that evolved greatly is not really something I can do, or even like :smile: 

I tested a little bit of Mavo and liked the idea though.
BTW, I didn't find how to deal with arrays in Mavo, nor how to link records and local storage is limited to 6MB, so I wonder about sqlite for offline and a REST API, with a preact or Vue for my PWA need.

If I'm wrong and PouchDB does the job (it seems abandoned, 22 PR waiting, last commit is sept 2019), or another way, please let me know.

**Comment by j2l** [comment]
Hello @LeaVerou 
I tried re-implemeting Mavo with GrapesJS and it doesn't show "Edit" in the top bar, only "Save".
Adding `<div id="gjs">` and `container: '#gjs',` into `grapesjs.init({` breaks Mavo.
Can't go further.
Would you please test it on your side?

Voici un très court exemple:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css" />
    <script src="https://get.mavo.io/mavo.js"></script>
    <script src="https://unpkg.com/grapesjs"></script>
    <title>Document</title>
</head>
<body>
    <div mv-app="Testing" mv-storage="local">
        <div id="gjs">
            <div property="complexPerson" mv-multiple>
                <span property="firstName">Lea</span>
                <span property="lastName">Verou</span>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var editor = grapesjs.init({
            height: '100%',
            container: '#gjs',
            fromElement: true,
        });
    </script>
</body>
</html>
```
